---

galaxy_info:
  author: amitpatole
  description: Tableau cluster for Linux.
  company: "myowncloud"
  license: "license (BSD, MIT)"
  min_ansible_version: 2.4
  platforms:
    - name: EL
      versions:
        - 6
        - 7
    - name: Fedora
      versions:
        - all
  galaxy_tags:
    - Tableau
    - Server
